apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  PERSONS_GRPC_URL: "person-grpc-service.svc.cluster.local:30008"
  KAFKA_URL: "kafka-0.kafka-headless.default.svc.cluster.local:9092"
  KAFKA_TOPIC: "location"
metadata:
  name: db-env