apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-consumer-api
  name: location-consumer-api
spec:
  selector:
    service: location-consumer-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-consumer-api
  name: location-consumer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-consumer-api
  template:
    metadata:
      labels:
        service: location-consumer-api
    spec:
      containers:
      - image: amh23/location-consumer-api:latest
        name: location-consumer-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: PERSONS_GRPC_URL
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: PERSONS_GRPC_URL
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_TOPIC        
      restartPolicy: Always
